apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: quarkus-serverless-function
spec:
  conclusion: >-
    You just learned how to create a Quarkus serverless function using Quarkus
    Funqy extension with OpenShift Serverless! To

    learn more about developing Kubernetes Native Java applications, take a look
    at our [Quarkus Guides](https://quarkus.io/guides/).
  description: >-
    Learn how to develop and deploy Quarkus serverless functions to Red Hat
    OpenShift.
  displayName: Get started with Quarkus serverless functions
  durationMinutes: 10
  icon: >-
    data:image/svg+xml;base64,PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMzQwMDt9LmNscy0ye2ZpbGw6I2NlMmUwMDt9LmNscy0ze2ZpbGw6bm9uZTt9LmNscy00e2ZpbGw6I2ZmZjt9LmNscy01e2ZpbGw6I2RjZGNkYzt9LmNscy02e2ZpbGw6I2FhYTt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZF9IYXQtT3BlbnNoaWZ0NC1DYXRhbG9nX0ljb25zLVNlcnZlcmxlc3M8L3RpdGxlPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiwxNC42NEE1MCw1MCwwLDAsMSwxNC42NCw4NS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik00MC41Nyw0Ny40MmEzLjg5LDMuODksMCwxLDAsMy44OCwzLjg4QTMuODksMy44OSwwLDAsMCw0MC41Nyw0Ny40MloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik0yMS40Miw0Ny40MkEzLjg5LDMuODksMCwxLDAsMjUuMyw1MS4zLDMuODksMy44OSwwLDAsMCwyMS40Miw0Ny40MloiLz48cGF0aCBjbGFzcz0iY2xzLTQiIGQ9Ik01MC4wOSw0OC44NmgtLjE4YTQuMTEsNC4xMSwwLDAsMS0zLjI2LTEuNjMsNy42OSw3LjY5LDAsMCwwLTEyLjE2LDAsNC4xMyw0LjEzLDAsMCwxLTMuMjYsMS42M0gzMWE0LjA5LDQuMDksMCwwLDEtMy4yNS0xLjYzQTcuNjksNy42OSwwLDAsMCwxNCw1MS45M2gwVjY0LjZhMi43OSwyLjc5LDAsMCwwLDIuNzksMi43OWgxNS44TDUxLjM0LDQ4LjY2QTQsNCwwLDAsMSw1MC4wOSw0OC44NloiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik03OC4wNSw0NC4yNWE3LjY1LDcuNjUsMCwwLDAtNS44NSwzQTQuMSw0LjEsMCwwLDEsNjksNDguODZoLS4xOWE0LjEzLDQuMTMsMCwwLDEtMy4yNi0xLjYzLDcuNjksNy42OSwwLDAsMC0xMi4xNiwwLDQuMTYsNC4xNiwwLDAsMS0yLDEuNDNMMzIuNjEsNjcuMzlIODMuMTlBMi43OSwyLjc5LDAsMCwwLDg2LDY0LjZWNTIuMDdBNy43Nyw3Ljc3LDAsMCwwLDc4LjA1LDQ0LjI1WiIvPjxwYXRoIGNsYXNzPSJjbHMtNiIgZD0iTTIxLjEsNjNoMTBhMS44MywxLjgzLDAsMSwwLDAtMy42NmgtMTBhMS44MywxLjgzLDAsMCwwLDAsMy42NloiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjQwLjU3IiBjeT0iMzcuNzMiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjQwLjU3IiBjeT0iMjguMjMiIHI9IjEuMzUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjU5LjcyIiBjeT0iMjguMjMiIHI9IjEuMzUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjIxLjQyIiBjeT0iMzcuNzMiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjUwIiBjeT0iNDMuNDUiIHI9IjIuOTMiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjY4Ljg5IiBjeT0iNDMuNDUiIHI9IjIuOTMiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjMxLjA5IiBjeT0iNDMuNDUiIHI9IjIuOTMiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNiIgY3g9Ijc3Ljk0IiBjeT0iNTQuMzEiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNiIgY3g9IjY4LjkxIiBjeT0iNTQuMzEiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9Ijc3Ljk0IiBjeT0iMzcuNzMiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjU5LjcyIiBjeT0iMzcuNzMiIHI9IjIuMTUiLz48Y2lyY2xlIGNsYXNzPSJjbHMtNCIgY3g9IjUwIiBjeT0iMzMuMSIgcj0iMy4wMSIvPjxjaXJjbGUgY2xhc3M9ImNscy00IiBjeD0iMzEuMDkiIGN5PSIzMy4xIiByPSIzLjAxIi8+PGNpcmNsZSBjbGFzcz0iY2xzLTQiIGN4PSI2OC44OSIgY3k9IjMzLjEiIHI9IjMuMDEiLz48L3N2Zz4=
  introduction: >-
    This quick start guides you through developing and deploying a Quarkus
    serverless

    function using Quarkus Funqy extension and OpenShift Serverless Function.
  nextQuickStart:
    - ''
  prerequisites:
    - ''
  tasks:
    - description: >-
        To launch CodeReady Workspaces:

        1. Click the **Application Launcher** icon in the top banner of the OpenShift
        Console. 
        
        2. Click the  **CodeReady Workspaces** item in the **Red Hat
        Applications** section to launch a new workspace.

        3. Log in with **DevSandbox**.

        4. A web browser or tab will open automatically. Click on **Create
        Workspace** on the left menu.

        5. Enter the following URL to **Git Repo URL** field:

        ```

        https://github.com/danieloh30/quarkus-funqy-qs.git

        ``` 

        5. Click on **Create & Open** to start your workspace. Note that it takes a few minutes to start
        a new workspace.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          #### To verify your new workspace was successfully created:
          Do you see a **quarkus-funqy-qs** item in the left Explorer menu and a message saying **Welcome To Your Workspace**?
      summary:
        failed: Try the steps again.
        success: You just created a new workspace in CodeReady Workspaces!
      title: Launch CodeReady Workspaces
    - description: >-
        To run Quarkus development mode (Live Coding) in CodeReady Workspaces:

        1. Click the **Cube** icon () on the right menu in your workspace.

        2. Expand **vscode-xxxxxx** in Plugins, and click on the **>_ New
        Terminal** command.

        3. Run the following Maven command in
        the new terminal window:

        ```

        mvn quarkus:dev

        ```

        Note that it might take a few minutes to download all dependencies and
        build the application at first.

        4. Click on **yes** to open the 8080 port on the popup message (_A new
        process is now listening on port 8080 but is listening on interface
        ::xxxx:xxxx:x which is internal..._).

        5. Click on **X** to close the debug popoup message (_A new process is
        now listening on port 5005 but is listening on interface 127.0.0.1 which
        is internal..._).
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          #### To verify the Quarkus development mode is running properly:

          Do you see the logs (_Profile dev activated. Live Coding activated._)
          in the terminal? 
      summary:
        failed: Try the steps again.
        success: >-
          You're now running the Quarkus development mode to activate the Live
          Coding!
      title: Run the Live Coding to develop new serverless functions
    - description: >-
        To test your first serverless function:

        1. In the project explorer, open the **MyFunctions.java** file in
        _src/main/java/org/acme_ directory.

        2. The **@Funq** annotation exposes the _hello_ method
        as a serverless function based on the **Funqy API**. The function name
        is equivalent to the method name (_hello_) by default:

        ```

        @Funq

        public String hello() {
            return "Welcome, Quarkus Serverless Functions on the Developer Sandbox!";
        }

        ```

        3. Open another terminal. 

        4. Enter the following curl command in the
        terminal to access the function:

        ```

        curl localhost:8080/hello ; echo

        ``` 
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          #### To verify that the function is accessible by the RESTful API:

          Do you see the output, **"Welcome, Quarkus Serverless Functions on the
          Developer Sandbox!"** in the terminal?
      summary:
        failed: Try the steps again.
        success: You just accessed your first serverless function locally!
      title: Test your first serverless function
    - description: >-
        Add a new function using Quarkus Contexts and Dependency Injection
        (CDI):

        1. Open the **MyFunctionsService.java** file in _src/main/java/org/acme_
        directory.

        2. Add the following code after **// Add a greeting service** line:

        ```

        public String greeting(String name) {
          return "Hello " + name;
        }

        ```

        Note that you don't need to save the file because CodeReady Workspaces
        will save the changes automatically.

        3. Open the existing **MyFunctions.java** file.

        4. Add the following code to inject the **MyFunctionsService**:

        ```

        @Inject

        MyFunctionsService myFunctionsService;


        @Funq

        public String greeting(String name) {
            return myFunctionsService.greeting(name);
        }

        ```

        5. Enter the following curl command in the
        terminal to access the new function:

        ```

        curl --data '"Quarkus Serverless Function"' localhost:8080/greeting ;
        echo

        ``` 
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          #### To verify that the new function is accessible by the RESTful API
          with a data:

          Do you see the output, **"Hello Quarkus Serverless Function"** in the
          terminal?
      summary:
        failed: Try the steps again.
        success: You just added a new serverless function to your Quarkus project!
      title: Add a new serverless function using Quarkus CDI
    - description: >-
        To deploy the functions to the OpenShift cluster on the developer
        sandbox:

        1. Open the **application.properties** file in _src/main/resources_
        directory.

        2. Uncomment the following configuration. Then, replace **USERNAME**
        with your username (e.g. _doh_). You can also find your username in
        OpenShift web console:

        ```

        quarkus.container-image.group=USERNAME-dev

<<<<<<< HEAD
=======
        }
>>>>>>> 250523b6992465eee2eabf68b02997c143bb4939

        ```

        3. Go back to OpenShift web console. Then, click on your **username**
        (e.g. _doh_) on the right top.

        4. Click on **Copy login command**. Note that a new web browser or tab
        will open automatically.

        5. Log in with **DevSandbox**.

        6. Click on **Display Token**.

        7. Copy the **oc** command with a token in **Log in with this token*.
        For example,

        ```

        oc login --token=sha256~h-QJe1mT7EWfO7xhOSfg9yZBd7QhWK0Y3qZVxb95IBY
        --server=https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443

        ```

        8. Go back to the terminal that Quarkus dev mode is running. Stop the
        dev mode by **CTRL-C**.

        9. Paste the above command to the terminal in CodeReady Workspaces. The
        output should look like:

        ```

        You have access to the following projects and can switch between them
        with 'oc project <projectname>':


        * YOUR_USERNAME-dev
          YOUR_USERNAME-stage

        Using project "YOUR_USERNAME-dev".

        Welcome! See 'oc help' to get started.

        ``` 

        9. Deploy the functions by using the following **Maven** command:

        ```

        mvn clean package

        ```

        Note that it takes a few minutes to complete building and deploying the
        applications to OpenShift.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          #### To verify that the Quarkus serverless functions are deployed
          successfully:

          Do you see the output,  **BUILD SUCCESS** in the terminal?
      summary:
        failed: Try the steps again.
        success: >-
          You just deployed your serverless functions to the OpenShift cluster
          on the developer sandbox!
      title: Deploy the Quarkus serverless function to OpenShift
    - description: >-
        To access the deployed functions on the OpenShift cluster:

        1. To change the displayed _OpenShift_ icon to **Quarkus**, Click on the
        **quarkus-funqy-qs-00001s** revision in Topology view.

        2. In the side panel, click the **Actions** dropdown menu and select
        **Edit labels**.

        3. Add an additional label: 

        ```

        app.openshift.io/runtime=quarkus

        ```

        4. Click on **Save** to save the labels.

        5. On the **Topology view** in Developer perspective, click on the
        displayed **OpenShift** icon. If the pod doesn't autoscale to `0` yet,
        leave the pod at least `30` seconds.

        6. Copy Route URL in **Routes** section on Resources view. For example,
        it should look like:

        ```

        https://quarkus-funqy-qs-doh-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com

        ```

        7. Enter the following **curl** command to access the **greeting** function.
        Be sure to replace **YOUR-ROUTE-URL** with the copied route URL in the CodeReady Workspaces terminal.

        ```

        curl --data '"Quarkus Serverless Functions"'
        https://YOUR-ROUTE-URL/greeting ; echo

        ```

        8. Go back to the **Topology view**. Then, make sure if the pod
        autoscales to `1`. Note that it takes a few seconds to scale out.

        9. Try to access the other function (**hello**) using the following curl
        command in the terminal after you replace **YOUR-ROUTE-URL** with your
        own URL:

        ```

        curl https://YOUR-ROUTE-URL/hello ; echo

        ``` 
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          #### To verify that the deployed functions on OpenShift are accessible
          by the RESTful APIs:

          1. Do you see the output, **"Hello Quarkus Serverless Function"** when
          you access the **greeting** function in the terminal?

          2. Do you see the output, **"Welcome, Quarkus Serverless Functions on
          the Developer Sandbox!"** when you access the **hello** function in
          the terminal?
      summary:
        failed: Try the steps again.
        success: You just accessed the deployed serverless functions on OpenShift!
<<<<<<< HEAD
      title: Access the functions on OpenShift
=======
      title: Access the functions on OpenShift
>>>>>>> 250523b6992465eee2eabf68b02997c143bb4939
